### ISSUE TITLE
Front Server SSL 설정

### ISSUE THREAD

**Issue by seung-gyu-kim** [nhnacademy-be5-staff99/store99-front#7]
https://www.rosehosting.com/blog/how-to-secure-nginx-with-lets-encrypt-on-ubuntu-20-04/

 - SSL 적용시 다음 사항을 고려 합니다.

   - L4에 SSL 인증서를 직접 등록하는 방법 ( L4 -> front server)

   - Nginx를 통해서 SSL인증서를 적용하고 L4를 이용해서 이중화 하는 방법 ( Nginx -> L4 -> front server)

**Comment by yrrho2** [comment]
nhn cloud의 store99-web보안 그룹에 SSL포트 443을 새로 열었습니다.
